# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:15.4
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm run test-ci
      - run:
          name: Copy tests results for storing
          command: |
            mkdir ~/test-results
            cp test-results.xml ~/test-results/
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results
    
workflows:
  cicd-demo:
    jobs:
      - build-and-test